/**
 * Auto-generated file detection guard.
 *
 * Prevents editing of files that appear to be automatically generated
 * by code generation tools (protoc, sqlc, buf, swagger, etc.).
 */
import * as fs from "node:fs/promises";
import { ToolError } from "./tool-errors";

/**
 * Number of bytes to read from the start of a file for auto-generated detection.
 */
const CHECK_BYTE_COUNT = 1024;

/**
 * Combined regex pattern to detect auto-generated file markers.
 * Matches all common conventions in a single pass.
 */
const AUTO_GENERATED_MARKER_RE =
	/(?:@generated|auto[-\s]?generat(?:ed|ion)|do(?:n'?t|\s+not)\s+(?:edit|modify)|code generated by|generated by\s+\w+|this file was automatically generated|protoc|sqlc|chisel|buf|swagger|openapi|grpc-gateway|mockery|stringer|easyjson|deepcopy-gen|defaulter-gen|conversion-gen|client-gen|lister-gen|informer-gen|zz_generated\.|\.pb\.|_pb2|\.gen\.|generated\.)/i;

/**
 * File name patterns that strongly indicate auto-generated files.
 * These are checked against the file name (not content).
 */
const AUTO_GENERATED_FILENAME_PATTERNS = [
	/^zz_generated\./,
	/\.pb\.(go|cc|h|c|js|ts)$/,
	/_pb2\.py$/,
	/_pb2_grpc\.py$/,
	/\.gen\.(go|ts|js|py)$/,
	/^generated\.(go|ts|js|py)$/,
	/\.swagger\.json$/,
	/\.openapi\.json$/,
	/\.mock\.(go|ts)$/,
	/\.mocks?\.(go|ts|js)$/,
];

/**
 * Check if a file name indicates it might be auto-generated.
 * This is a quick pre-check before reading file content.
 */
function isAutoGeneratedFileName(filePath: string): boolean {
	const fileName = filePath.split("/").pop() ?? "";
	return AUTO_GENERATED_FILENAME_PATTERNS.some(pattern => pattern.test(fileName));
}

/**
 * Check if content prefix contains auto-generated markers.
 * Returns the matched marker text if found, null otherwise.
 */
function detectAutoGeneratedMarker(content: string): string | null {
	const match = AUTO_GENERATED_MARKER_RE.exec(content);
	if (match) {
		return match[0];
	}
	return null;
}

/**
 * Read the first N bytes of a file as a UTF-8 string.
 * More efficient than reading the entire file.
 */
async function readFilePrefix(path: string, bytes: number): Promise<string | null> {
	const handle = await fs.open(path, "r").catch(() => null);
	if (!handle) {
		return null;
	}

	try {
		const buffer = Buffer.allocUnsafe(bytes);
		const { bytesRead } = await handle.read(buffer, 0, bytes, 0);
		return buffer.toString("utf-8", 0, bytesRead);
	} catch {
		return null;
	} finally {
		await handle.close();
	}
}

/**
 * Build the error message for an auto-generated file.
 */
function buildAutoGeneratedError(displayPath: string, detected: string): ToolError {
	return new ToolError(
		`Cannot modify auto-generated file: ${displayPath}\n\n` +
			`This file appears to be automatically generated (detected marker: "${detected}").\n` +
			`Auto-generated files should not be edited directly. Instead:\n` +
			`1. Find the source file or generator configuration\n` +
			`2. Make changes to the source\n` +
			`3. Regenerate the file`,
	);
}

/**
 * Check if a file is auto-generated by examining its content.
 * Throws ToolError if the file appears to be auto-generated.
 *
 * @param absolutePath - Absolute path to the file
 * @param displayPath - Path to show in error messages (relative or as provided)
 */
export async function checkAutoGeneratedFile(absolutePath: string, displayPath?: string): Promise<void> {
	const pathForDisplay = displayPath ?? absolutePath;

	// First check file name as a quick filter
	if (isAutoGeneratedFileName(absolutePath)) {
		const fileName = absolutePath.split("/").pop() ?? "";
		throw buildAutoGeneratedError(pathForDisplay, fileName);
	}

	// Read only the first N bytes for content check
	const content = await readFilePrefix(absolutePath, CHECK_BYTE_COUNT);
	if (content === null) {
		// If we can't read the file, let the caller handle it
		return;
	}

	const marker = detectAutoGeneratedMarker(content);
	if (marker) {
		throw buildAutoGeneratedError(pathForDisplay, marker);
	}
}

/**
 * Check if file content is auto-generated.
 * Uses only the first CHECK_BYTE_COUNT characters of the content.
 * Throws ToolError if the content appears to be auto-generated.
 *
 * @param content - File content to check (can be full content or prefix)
 * @param displayPath - Path to show in error messages
 */
export async function checkAutoGeneratedFileContent(content: string, displayPath: string): Promise<void> {
	// Only check the prefix for efficiency
	const prefix = content.slice(0, CHECK_BYTE_COUNT);
	const marker = detectAutoGeneratedMarker(prefix);
	if (marker) {
		throw buildAutoGeneratedError(displayPath, marker);
	}
}
